from _typeshed import Incomplete

DATA_STORE: str
UPLOAD: str
URL_INPUT: str
DATA_LOADER_BUTTON: str
TAS: str
TAS_DIAGRAM: Incomplete
TAS_DIAGRAM_CONTAINER: Incomplete
TAS_DIAGRAM_LOCATION_DROPDOWN: Incomplete
TAS_DIAGRAM_LOCATION_SELECT_ALL_BUTTON: Incomplete
TAS_DIAGRAM_X_AXIS_DROPDOWN: Incomplete
TAS_DIAGRAM_Y_AXIS_DROPDOWN: Incomplete
